spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    username: root
    password:
  profiles: dev
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  type-aliases-package: yun.beans
eureka:
  client:
    service-url:
      defaultZone: http://eureka7006.com:7006/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: provider8001
    prefer-ip-address: true
---
server:
  port: 8002
spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb02
    username: root
    password:
  profiles: test
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  type-aliases-package: yun.beans
eureka:
  client:
    service-url:
      defaultZone: http://eureka7006.com:7006/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: provider8002
    prefer-ip-address: true
